package cn.edu.ustc.sse.workorder.bean;

public class ParaentCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paraentcategory.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paraentcategory.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paraentcategory.id
     *
     * @return the value of paraentcategory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paraentcategory.id
     *
     * @param id the value for paraentcategory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paraentcategory.name
     *
     * @return the value of paraentcategory.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paraentcategory.name
     *
     * @param name the value for paraentcategory.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}